//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.20 at 05:20:40 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://thomas-bayer.com/blz/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webservices.examplesoapclient.stub;
